# modified from: https://linuxhint.com/lamp_server_docker/
# Use root/example as user/password credentials
version: '3.1'

services:
  web-server:
    build:
      dockerfile: Dockerfile/php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"

  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
    volumes:
      #- /usr/local/mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql
      # load SQL from ./mysql directory
      - ./mysql/:/docker-entrypoint-initdb.d
    ports:
      - 3000:3306
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: password 
    ports:
      - "5000:80"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password 
    volumes:
        - mongo-data:/data/db/
        - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - 2000:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  mysql-data:
  mongo-data:
